GET http://localhost:5228/games

###
GET http://localhost:5228/games/1

###
POST http://localhost:5228/games
Content-Type: application/json

{
    "name" : "Final Fantasy",
    "genreId":2,
    "price":59.99,
    "releaseDate":"2010-11-18"
}

###
PUT http://localhost:5228/games/5
Content-Type: application/json

{
    "name" : "Minecraft",
    "genre":"Kids and Family",
    "price":9.99,
    "releaseDate":"2011-11-18"
}

###
DELETE http://localhost:5228/games/1
